--- !ditz.rubyforge.org,2008-03-06/project 
name: HsOpenSSL
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: HsOpenSSL
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: HsOpenSSL-0.10.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-08-05 08:08:53.735865 Z
    - PHO <pho@cielonegro.org>
    - created
    - |-
      This release will include the following patches from Mikhail Vorozhtsov:
      * Added optional verification callback to VerifyPeer.
      * Expose low-level asynchronous versions of accept, connect, read, write and s
      hutdown.
